services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python main.py
    volumes:
      - .:/backend
    ports:
      - 5500:5500