services:
  backend_receiver:
    container_name: backend_receiver
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python app_receiver.py
    volumes:
      - .:/backend
    ports:
      - 5501:5501
    depends_on:
      - rabbitmq

  backend_sender:
    container_name: backend_sender
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: python app_sender.py
    volumes:
      - .:/backend
    ports:
      - 5500:5500
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

volumes:
  rabbitmq_data: